# Generated by Django 4.2 on 2023-04-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
